### ISSUE TITLE
Getting title from client-side is not cool

### ISSUE THREAD

**Issue by BatuhanK** [ademilter/salyangoz-me-feedback#1]
<img width="829" alt="screen shot 2016-05-29 at 15 27 59" src="https://cloud.githubusercontent.com/assets/4688083/15633299/e97aa50a-25b1-11e6-82ee-42adfcab7cf7.png">
I think webpages' title data must fetched from server

**Comment by BatuhanK** [comment]
And also you can send very very very long titles:

<img width="908" alt="screen shot 2016-05-29 at 15 45 58" src="https://cloud.githubusercontent.com/assets/4688083/15633391/8e4273cc-25b4-11e6-8c82-1447f3e707eb.png">

<img width="1369" alt="screen shot 2016-05-29 at 15 46 13" src="https://cloud.githubusercontent.com/assets/4688083/15633394/94fb90cc-25b4-11e6-93f6-bc658d9b250c.png">

**Comment by askn** [comment]
thanks 👍 👊

**Comment by BatuhanK** [comment]
@askn what if I send this url right now: http://ipv4.download.thinkbroadband.com/1GB.zip ?

**Comment by askn** [comment]
Teşekkürler @BatuhanK 👍 Gerekli iyileştirmeyi yaptık
