### ISSUE TITLE
Unhandled sql error on relationship pages

### ISSUE THREAD

**Issue by BatuhanK** [ademilter/salyangoz-me-feedback#2]
If you try to follow a user which you are already following, you are getting error message like this.

<img width="1063" alt="screen shot 2016-05-29 at 15 36 14" src="https://cloud.githubusercontent.com/assets/4688083/15633341/4cc93f58-25b3-11e6-9884-9f4b84136727.png">

And if you try to unfollow a user which you are not following: 

<img width="1001" alt="screen shot 2016-05-29 at 15 39 25" src="https://cloud.githubusercontent.com/assets/4688083/15633349/99c33016-25b3-11e6-9b60-afcaad28b9a5.png">

**Comment by BatuhanK** [comment]
ruby says:

app/models/user.rb:39:in `follow'
app/controllers/users_controller.rb:37:in `follow'

**Comment by askn** [comment]
👍 🎉
