### ISSUE TITLE
(possible) Duplicate usernames

### ISSUE THREAD

**Issue by BatuhanK** [ademilter/salyangoz-me-feedback#4]
I'm not sure but I believe there is 2 http://salyangoz.me/bthn03967 right now.
Can you check it?
(I inferred that from follow/unfollow button on my profile page)

Steps to reprocedure:

1- login salyangoz via Twitter
2- change your Twitter username to anything else
3- login to another Twitter account and change it's username to first account's old username
4- now login salyangoz via Twitter again

![duplicate-usernames](https://cloud.githubusercontent.com/assets/4688083/15633577/159913b8-25b9-11e6-84cc-b35cf8ca7ac2.gif)

**Comment by askn** [comment]
Thanks 👍
